### ISSUE TITLE
Watanagashi DLL translates script commands to wrong operation

### ISSUE THREAD

**Issue by EliEron** [07th-mod/higurashi-dlls#1]
The new Watanagashi DLL does not work quite right, so I decided to experiment a bit to try to figure out what its doing incorrectly.

I did a ton of testing and made some interesting discoveries along the way, but to cut a long story short what I discovered is that the new DLL seems to translate the custom script commands (ModPlayVoiceLS, ModDrawCharacter, ModDrawCharacterWithFiltering, etc ) to a different C# operation than they are supposed to. This translation happens when the files in the CompiledUpdateScripts folder is created on first boot.

When ModPlayVoiceLS appears in the script the game tries to call OperationModDrawCharacter, when ModDrawCharacter is called the game tries to run OperationMODNVLADVModeSettingLoad.

In other words the parameters from the script is passed to the wrong C# method.

Here is a list of the command translations I came across:

ModPlayVoiceLS -> OperationMODDrawCharacter
ModDrawCharacter -> OperationMODNVLADVModeSettingLoad
ModDrawCharacterWithFiltering -> OperationMODCallScriptSection

I came to this conclusion partly by studying the output_log the game generates when it crashes, and partly due to the fact that I observed that the files in CompiledUpdateScripts where different when the new DLL was used to generate them compared to generating them with P-Chang's DLL.

An interesting thing I discovered was that if you use P-Chang's Watanagashi lipsync DLL ([download](http://www.mediafire.com/file/3jo7o9p5os6w62k/Assembly-CSharp-spectrum.zip
)) on the first boot, then replace P-Chang's DLL with the new Watanagashi DLL the game will run fine with lipsync working perfectly.

Meaning that the new Watanagashi DLL works fine at executing the custom commands once they have been compiled in the CompiledUpdateScripts folder. The fault is that it does not generate those compiled files correctly on its own.

**Comment by enumag** [comment]
I believe each of those operations has some sort of numerical ID in the DLL. My guess is that those IDs are stored in the compiled scripts and used to execute the right function when playing. This is probably just a copy-paste error - the IDs are probably a little different than in Oni so straight copy paste wouldn't work. Perhaps the `BurikoOperations.cs` file is where the bug is.

Thanks for the detailed explanation!

**Comment by EliEron** [comment]
Since I already spent some time investigating this issue I decided to take a look at the DLL itself just in case I could figure out the faulty code. And I in fact managed to do so.

The issue is in fact not in the enumerations that are present in `BurikoOperations.cs`, but in a file called `OperationHandler.cs`.

That class is a part of the BGICompiler which is the part of the DLL that is responsible for translating the BGI-Style script into compiled MG files. The class has a method called `FillParamValues` which populates a `<string, int>` dictionary called `paramLookup` with mappings between a script command and an ID that corresponds to a C# operation.

At  the bottom of this method you can find these three lines:

```C#
OperationHandler.paramLookup.Add("ModDrawCharacter", new OpType(BurikoOperations.ModNVLADVModeSettingLoad, "iissiiibiiiiiiiiib"));
OperationHandler.paramLookup.Add("ModDrawCharacterWithFiltering", new OpType(BurikoOperations.ModCallScriptSection, "iisssiiibiiiiiiib"));
OperationHandler.paramLookup.Add("ModPlayVoiceLS", new OpType(BurikoOperations.ModDrawCharacter, "iisib"));
```

Just by reading them it should be pretty obvious what the issue with those three lines are. By patching them into the correct lines like this:

```C#
OperationHandler.paramLookup.Add("ModDrawCharacter", new OpType(BurikoOperations.ModDrawCharacter, "iissiiibiiiiiiiiib"));
OperationHandler.paramLookup.Add("ModDrawCharacterWithFiltering", new OpType(BurikoOperations.ModDrawCharacterWithFiltering, "iisssiiibiiiiiiib"));
OperationHandler.paramLookup.Add("ModPlayVoiceLS", new OpType(BurikoOperations.ModPlayVoiceLS, "iisib"));
```

The DLL works correctly. I have uploaded a patched DLL [here](http://www.mediafire.com/file/xemf334llxuvujw/Assembly-CSharp-fixed.zip).

**Comment by DoctorDiablo** [comment]
Nice work.  Looks like I just copied some of the code in wrong.  Thanks for taking the time to fix it.
