### ISSUE TITLE
Select() options too close together

### ISSUE THREAD

**Issue by DoctorDiablo** [07th-mod/higurashi-dlls#13]
@idealpersona 
![image](https://user-images.githubusercontent.com/20390474/39104911-997e50aa-4680-11e8-8d12-e16659b09ef5.png)
![image](https://user-images.githubusercontent.com/20390474/39104949-c9f9a6ee-4680-11e8-8b19-cff2aa0cfb39.png)

The chapter select screen in the console arcs is implemented using the Select() function in the scripts.  Unfortunately, all the options occupy the same narrow section of the screen no matter how many options are in the list... so text starts to overlap when you have 4+ options. (and I'm hoping to have 10 options total, one day!)  Would be better if each option was just drawn a fixed number of pixels below the previous option.

Edit: Also there's an [old issue](https://github.com/07th-mod/higurashi-console-arcs/issues/10) in that same piece of functionality that causes the text to be drawn off-center.  Probably relatively easy to fix that at the same time.

**Comment by DoctorDiablo** [comment]
![image](https://user-images.githubusercontent.com/20390474/40571003-3177a03a-605f-11e8-868a-460b0a992984.png)

Ok, I've got a mostly-working fix for this, but I'm not 100% satisfied yet.  This is what I've changes so far:

- Inside ChoiceController.Create() I tweaked this one line to get the options centered and able to display all 11 options at once:
`gameObject2.transform.localPosition = new Vector3(-150f, (float)(-50 * i + 27 * count), 0f);`

- In BurikoScriptFile.OperationSelect() I added this line before the DisplayChoices() call to hide the screen filter:
`this.gameSystem.MainUIController.HideLayerBackground(0.25f);`

- In MainUIController I changed the scope of the HideLayerBackground() function to public so that OperationSelect could access it.

The screen filter flashes onscreen for a second before my change is able to 
hide it, and I'd prefer it didn't.  I'm still trying to track down what's drawing it in the first place.  I'm also looking into splitting it into a 2 column layout or maybe 2 separate windows, because the screen looks a bit cluttered with everything together.

**Comment by enumag** [comment]
2 columns with back button in bottom center would be good in my opinion.

**Comment by DoctorDiablo** [comment]
Got the 2 column layout working.  I need to create a new scenario image to add the buttons and icons behind the text.  I'm thinking of making the currently-implemented ones red and the un-implemented ones gray.

![image](https://user-images.githubusercontent.com/20390474/40578147-2138c07c-60dd-11e8-9de3-3a5532dbb500.png)

And I made sure it didn't break the TIPS screen, which also uses the Select() function
![image](https://user-images.githubusercontent.com/20390474/40578167-75252ebe-60dd-11e8-938e-1961cc7878e1.png)

**Comment by enumag** [comment]
@DoctorDiablo Sounds good. I think I'd move all the options a bit down and maybe add some distance between the choices and the back button.

**Comment by ghost** [comment]
Could this modification mess up anything else in the game? Wondering whether it is preferable to implement only in Hima for the console arcs or for all arcs to make things consistent. The only other event with a choice in the game that I recall is the TIP that lets you choose between the two boxes.  Not sure which arc that was, but it very well could have been Hima.
Edit: sorry, i need to stop accidentally hitting "Close and comment"

**Comment by DoctorDiablo** [comment]
There's one tip in Hima that has a choice dialog, but that's the only one in all the chapters released so far.  I actually built the console arcs release around Hima specifically because that choice functionality was there.  I think Minagoroshi has a choice too, but we can worry about that when it becomes relevant.

So, there's no need to port it to the other chapters, other than for the sake of consistency.  Or perhaps if we ever decide to add the choices from Sui into the main series.

**Comment by ghost** [comment]
Let's start with just doing this on Hima and document that it's only done there.  We can also choose to make this transform optional, triggered by a new global flag.  Edit: or make an update to the scripting layer to support this in a more elegant way, but it would be more work, possibly with the slight upside that it's very obvious other arcs don't have this functionality if they were missing a new command or something.

**Comment by DoctorDiablo** [comment]
Fixed as of 784f2519d59c889e730b9b9eecda28d897a978c5
