### ISSUE TITLE
Tips screen for console arcs

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-dlls#15]
Currently tips in the console arcs are just appended to the day where they're unlocked.

It would be better to use the regular tips screen for these tips, same as the main arcs.

In order to avoid separate dll for Hima and console arcs this requires a config file (JSON?) where the configuration for the tips screen would be located.

**Comment by ghost** [comment]
Dependent on #25

**Comment by ghost** [comment]
I think it's down to scripting now with #25 in place.  It looks like `flow.txt` contains scripting for the TIPs menu.  There's a bit of conflict here where the tips are programmed to be kind of global, but we might be able to have the same kind of selection we have on the start menu to pick an arc, and that will just set the GArc variable accordingly.  When the TIPs screen loads, it should be loading the tips associated with this variable anyway.  I would suggest some kind of cleanup if possible when that screen exits (or maybe upon each time loading that title screen) to reset the flag.  @DoctorDiablo does this sound reasonable to you?

**Comment by DoctorDiablo** [comment]
Fixed as of 784f2519d59c889e730b9b9eecda28d897a978c5
