### ISSUE TITLE
Configuration file support

### ISSUE THREAD

**Issue by ghost** [07th-mod/higurashi-dlls#19]
There's been a number of cases discussed lately where it would be nice to be able to load a configuration file and use settings therein for hard-coded values in the code.  This includes TIPS, text values that people want to localize, and toggles for behavior special to the console arcs.  This could potentially be JSON, YAML, etc.  These cases can be solved individually without such a file but it seems like it would make things easier to implement those features if something like this was already set up.

**Comment by ghost** [comment]
I have pushed a prototype DLL for this on the `config` branch.  I did it for Tsumi so far and will port to the other arcs.

The configuration file must either not exist or be a valid JSON object and is expected to appear at `StreamingAssets/nipah.json`

Here is an example so far to support #17:

```
{
	"SaveSubdirectory": "console"
}
```

The deserialized key-value pairs must appear as public properties in `MOD.Scripts.Core.Config.MODConfig` (i.e., the only one present right now is a string property called `SaveSubdirectory` in order to be deserialized.  If any MODConfig property is not present in the configuration file, the default will be used for that datatype.  We are able to customize defaults if needed.

**Comment by ghost** [comment]
By @enumag 's suggestion, this is now put into the data folder instead of streaming assets.

**Comment by enumag** [comment]
@idealpersona Is this implemented in the master branch for all chapters? Can we use if to add some new features such as more textboxes?

**Comment by ghost** [comment]
Added to all arcs
