### ISSUE TITLE
TIPS outside of DLL

### ISSUE THREAD

**Issue by ghost** [07th-mod/higurashi-dlls#25]
Currently the TIPs are hard-coded into the DLL.  This is bad for a number of reasons.  If we move to a separate file (e.g. JSON) then we can better support localization efforts and console arcs.

**Comment by ghost** [comment]
Prototype DLL is done for Hima on the `tips` branch. @DoctorDiablo feel free to try it out.  as with the config file, there can be a separate `tips.json` in the same directory containing tips.  The Deserialized type is `Dictionary<int, List<TipsDataEntry>>` (where TipsDataEntry is from the vanilla DLL.  The key is the arc number, which is 0 by default, and the values are the list of tips.  It's up to you how you want to enumerate the arcs.

The DLL uses a new **non-global** flag `GArc` to store the arc number (again, 0 by default), and when tips are fetched, they grab that list associated with that arc number's current value.  If you want to change this value, I believe this flag is SetFlag.  I did non-global because it should be based on the current save and not apply for all future sessions.  We'll need to test this out more to see how this plays with saving and loading existing games.  I figure at a minimum, the arc menu script can just have a command to set the desired arc number whenever an arc is clicked to get started.

If the tips file is not present, it defaults back to the hard-coded Tips.  If the file is present but contains no entry for the current arc, it is treated as having 0 Tips.

@enumag Aside from the console arc difficulties, this should work effectively for the regular arcs now.  Here is an example tips.json for hima only.  I changed the title of one and verified that it showed up modified in the menu.

```
{
	0 : [
	  {
		"Id": 64,
		"Title": "Phone Call with Yukie",
		"TitleJp": "雪絵との電話",
		"Script": "hima_tips_01",
		"UnlockChapter": 1
	  },
	  {
		"Id": 65,
		"Title": "A Record of Opening Remarks",
		"TitleJp": "来賓挨拶用原稿",
		"Script": "hima_tips_02",
		"UnlockChapter": 1
	  },
	  {
		"Id": 66,
		"Title": "Gears and Fire and the Taste of Honey",
		"TitleJp": "歯車と火事と蜜の味",
		"Script": "hima_tips_03",
		"UnlockChapter": 1
	  },
	  {
		"Id": 67,
		"Title": "The Chick in the Trunk",
		"TitleJp": "トランクの雛",
		"Script": "hima_tips_04",
		"UnlockChapter": 1
	  },
	  {
		"Id": 68,
		"Title": "Going Smoothly",
		"TitleJp": "順調",
		"Script": "hima_tips_05",
		"UnlockChapter": 2
	  },
	  {
		"Id": 69,
		"Title": "Why I Like Rainy Days",
		"TitleJp": "雨雲に恋して",
		"Script": "hima_tips_06",
		"UnlockChapter": 2
	  },
	  {
		"Id": 70,
		"Title": "Barley Tea and Black Tea and a Millstone",
		"TitleJp": "麦茶と紅茶と石臼と",
		"Script": "hima_tips_07",
		"UnlockChapter": 2
	  },
	  {
		"Id": 71,
		"Title": "The Investigation Runs Aground",
		"TitleJp": "調査は暗礁",
		"Script": "hima_tips_08",
		"UnlockChapter": 3
	  },
	  {
		"Id": 72,
		"Title": "What's in the Box?",
		"TitleJp": "箱選びゲーム",
		"Script": "hima_tips_09",
		"UnlockChapter": 3
	  },
	  {
		"Id": 73,
		"Title": "The Glint in the Demon's Eye",
		"TitleJp": "鬼の目にも何とか",
		"Script": "hima_tips_10",
		"UnlockChapter": 3
	  },
	  {
		"Id": 74,
		"Title": "A Very Kind Person",
		"TitleJp": "とてもやさしい人なの",
		"Script": "hima_tips_11",
		"UnlockChapter": 4
	  },
	  {
		"Id": 75,
		"Title": "Mother's Diary",
		"TitleJp": "母の日記",
		"Script": "hima_tips_12",
		"UnlockChapter": 5
	  },
	  {
		"Id": 76,
		"Title": "Mother's Diary",
		"TitleJp": "母の日記",
		"Script": "hima_tips_13",
		"UnlockChapter": 5
	  },
	  {
		"Id": 77,
		"Title": "Mother's Diary",
		"TitleJp": "母の日記",
		"Script": "hima_tips_14",
		"UnlockChapter": 5
	  }
	]
}
```

**Comment by enumag** [comment]
@idealpersona It's most likely not very useful for us until we have a solution for 07th-mod/higurashi-assembly#149 which will be quite difficult. But it's certainly a step forward and I'm sure those who are translating the games to other languages will appreciate it. Thank you!
