### ISSUE TITLE
Build from (decompiled) source

### ISSUE THREAD

**Issue by ghost** [07th-mod/higurashi-dlls#6]
This would be a very nice to have.

DNSpy - though a nice tool - does not have a good development workflow.

- Changes must be made one file at a time and **must compile** when finished.
- Despite that they must compile, changes in one class are not visible to others until the assembly file is rewritten.
- While editing a file you cannot unfocus the editor window to examine other code
- Changes we make for good style may not persist through the compiler optimizations.
- We sometimes have to re-implement pieces of code to cover for decompiler failures.

And in general, making binary changes prevent us from being able to see text diffs and to take full advantage of git and github features accordingly.

Recently I had to change a method and add a parameter to it.  I had to make a new overload of that method with the extra argument, point all references to that new overload, and I still got errors.  Why? It took some digging, but it appeared to be because dependent component's IL assembly contained subroutines used to set up and invoke the actual method call, so although I updated the C# code to point to the new reference, the underlying module was still referencing it.  Removing those subroutines solved it.  So these are surmountable constraints, but far from ideal or effective.

So ideally we can develop and build from source and have a more natural development workflow.  My first stab would be to see if we can just gather the dependencies and have Mono compile them.

**Comment by TellowKrinkle** [comment]
[ILSpy](https://github.com/icsharpcode/ILSpy) has the ability to automatically generate `.csproj` files.  When I tried it, it messed up decompilation of a few files but once I replaced the messed up methods with code from DNSpy (it inserts comments starting with `/*Error` so they're easy to find), I was able to use the Mac version of Visual Studio (I would assume the Windows version will work too) to compile a dll that worked well enough to (seemingly) run the game fine.

**Comment by ghost** [comment]
I think we can safely report success with this effort.  Thank you @tellowkrinkle !  The code is currently at https://github.com/07th-mod/higurashi-assembly so it may be all merged into here or that may become the new home for DLL code.
