### ISSUE TITLE
Lipsync animation does not stop when audio is cut off

### ISSUE THREAD

**Issue by ghost** [07th-mod/higurashi-dlls#8]
When one skips forward the dialogue before the audio and lipsync animation is complete, the lipsync animation may continue to completion even though that line's voice audio is cut off.

The lipsync animation should end with the audio.  As in #5 when it ends it should return to the original expression, not just halt in place.

**Comment by DoctorDiablo** [comment]
So the way I was imagining it, we just need to do a check every time we call MODPlayVoice LS to see if any previous lipsync animations are playing on the same audio channel as the current MODPlayVoiceLS call and then tell them to stop.  Looks like there's already an array that stores the mapping between characters and channels in MODSceneController.MODLipSync_Layer that we can use.  Hopefully the existing code is populating it for us.

```
public void MODPlayVoiceLS(string filename, int channel, float volume, int character)
{
    for (int i=0;i<MODLipSync_Layer.size;i++) {
        if (MODLipSync_Layer[i]==channel and i!=character) {
            MODLipSync_Bool[i]=false; //tells the scenecontroller to disable this character's lipsync
            MODLipSync_Layer[i]=0; //disassociate that character with that channel so we don't mix it up later
        }
    }
    //do the rest of the existing lipsync processing
}
```

Then we also need to modify MODDrawLipSync to check MODLipSync_Bool during each iteration of the loop to determine if the animation needs to end prematurely, and then break out of the loop if so.

**Comment by ghost** [comment]
@DoctorDiablo regarding `if (MODLipSync_Layer[i]==channel and i!=character)`, i'm wondering if ` and i!=character` is needed to be in place.  Else it seems like we're explicitly accommodating the case where a character has two lipsyncs going simultaneously!

**Comment by DoctorDiablo** [comment]
That may not be necessary, but I put that there to handle the (pretty typical) case where a character says multiple lines in a row.  There's no sense stopping a character's animation if it's just going to start again a moment later.

We can try it both ways and pick whichever one works better.

**Comment by ghost** [comment]
The solution now present in oni through tatari is as follows:

- Maintain state for the last audio channel used by each character
- When voice plays, disable lipsync for any other character who has last used that channel
- While looping through the lipsync animation, check during each iteration whether lipsync is still enabled for that character

However, if A and B are on the screen, and A talks, then B talks, and then A talks, A's lipsync won't work because by these rules, B's voice event disabled A's lipsync until another ModDrawCharacter changes A's sprite.  So we added this one condition:

- When voice plays, enable lipsync if for that character

However, that had the side effect of the game trying to lip-sync characters who are off-screen, to hilarious and disastrous results.  This most importantly includes Keiichi.  Additional condition:

- In addition to checking the flag for that character, animate lipsync only when the character has been drawn on the screen and is still there on the same layer it was drawn before.
